
name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Change it to your OS

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies

      - name: Run Python script
        run: python test.py # Change it to your Python file name

